import type { Metadata } from 'next';
import { montserrat } from '@assets/fonts';
import { SpeedInsights } from '@vercel/speed-insights/next';

import '@styles/globals.css';

export const metadata: Metadata = {
    title: 'Strony Na Grubo',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pl">
            <body className={montserrat.className}>{children}</body>
            <SpeedInsights />
        </html>
    );
}
